### ISSUE TITLE
Check for and update broken links in "in the wild"

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#180]
@kittarlin While you're in there you might run through everything and make sure it's all still working.

**Comment by kittarlin** [comment]
deepzoom.py is no longer being maintained.  Do you want to keep it in the list?

Node.js Deep Zoom Tools might no longer be under construction.  Should the text be updated?

Otherwise, the links all look ok to me.

**Comment by kittarlin** [comment]
Sorry, that last list is for the Creating page.   On the In the Wild page:

Karina Twiss no longer seems to be using OSD on her site.  I've hidden her.
Maxotics' images on the link we have don't seem to work.  Replaced that link with a link to the DigiTiler gallery.
Sweden's National Museum is closed til fall 2018.  I've hidden the link to them, since their site is throwing 500 errors.
Family Search has their stuff behind a login, so it's not possible to link to a specific image (census page).  Do you want to leave them in the list?
The Bibliotheque Nationale de France link is claiming that maintenance has shut it down.  The sublink to Gallica does work, but I don't think the images there are OSD.

More to come.  Let me know what changes should be made based on the notes above.

**Comment by iangilman** [comment]
Linking to unmaintained projects is fine; maybe someone will pick up the torch. Do please take the "under construction" off of the node.js one.

Thanks for finding the "in the wild" links that are broken and hiding them!

The Swedish National Museum site is still working for me... Maybe the 500s were just a glitch?

We should hide Family Search, but it might be amusing to contact them and see if they do have an OSD example available outside of the signin. And yes, let's hide The Bibliotheque Nationale de France; I agree it doesn't look like OSD.

**Comment by iangilman** [comment]
This has been fixed by #179.
